# Generated by Django 5.1.2 on 2024-11-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token', 'ip_address'], name='refresh_tok_token_7a9ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['created'], name='refresh_tok_created_32b2d8_idx'),
        ),
    ]
