# Generated by Django 5.1.2 on 2024-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='아이디'),
        ),
    ]
