# Generated by Django 5.1.2 on 2024-11-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provider_id',
        ),
    ]
