# Generated by Django 5.1.2 on 2024-11-06 06:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0002_remove_user_image_url_remove_user_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('provider', models.CharField(max_length=32, verbose_name='소셜로그인')),
                ('uid', models.CharField(max_length=254, verbose_name='소셜로그인 식별자')),
                ('extra_data', models.TextField(verbose_name='추가 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road2gm.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
