# Generated by Django 5.1.2 on 2024-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0002_refreshtoken_refresh_tok_token_7a9ce0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
    ]
