# Generated by Django 5.1.2 on 2024-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0003_remove_user_refresh_token_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP 주소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=128, verbose_name='토큰'),
        ),
        migrations.AlterUniqueTogether(
            name='refreshtoken',
            unique_together={('token', 'ip_address')},
        ),
    ]
