# Generated by Django 5.1.2 on 2024-11-02 14:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0003_user_user_usernam_b79065_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='아이디')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road2gm.role', verbose_name='부모')),
            ],
            options={
                'verbose_name': '역할',
                'verbose_name_plural': '역할',
                'db_table': 'role',
            },
        ),
    ]
