# Generated by Django 5.1.2 on 2024-11-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0003_socialaccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccounts',
            options={'verbose_name': '소셜연동계정', 'verbose_name_plural': '소셜연동계정'},
        ),
        migrations.AlterModelTable(
            name='socialaccounts',
            table='social_account',
        ),
    ]
