# Generated by Django 5.1.2 on 2024-11-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0004_alter_socialaccounts_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialAccounts',
            new_name='SocialAccount',
        ),
    ]
