# Generated by Django 5.1.2 on 2024-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0005_rename_socialaccounts_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='username',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
