# Generated by Django 5.1.2 on 2024-11-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0005_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='parent',
        ),
    ]
