# Generated by Django 5.1.2 on 2024-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road2gm', '0007_socialaccountstate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialAccountState',
            new_name='OAuth2Token',
        ),
        migrations.RemoveIndex(
            model_name='oauth2token',
            name='social_acco_state_f5e850_idx',
        ),
        migrations.RenameField(
            model_name='oauth2token',
            old_name='state',
            new_name='token',
        ),
        migrations.RenameIndex(
            model_name='oauth2token',
            new_name='oauth2_toke_created_ccbb8d_idx',
            old_name='social_acco_created_c43f4b_idx',
        ),
        migrations.AddIndex(
            model_name='oauth2token',
            index=models.Index(fields=['token'], name='oauth2_toke_token_4bdcbd_idx'),
        ),
        migrations.AlterModelTable(
            name='oauth2token',
            table='oauth2_token',
        ),
    ]
